---
deployment:
  tasks:
    - export DEPLOYPATH=/home/datacent/respaldoreportedelabores.datacenterpc.com
    - /bin/cp -f start-server.js $DEPLOYPATH/start-server.js
    - /bin/cp -f next.config.ts $DEPLOYPATH/next.config.ts
    - /bin/cp -rf .next $DEPLOYPATH/.next
    - /bin/cp -rf public $DEPLOYPATH/public
    - /bin/cp -f .env $DEPLOYPATH/.env
    - /bin/cp -f package.json $DEPLOYPATH/package.json
